### ISSUE TITLE
最近APIサーバのプロトタイプがオフになっている

### ISSUE THREAD

**Issue by AndrewDang-Tran** [aozorahack/pubserver2#6]
すみません日本語はあまりかきません．

今，`curl http://pubserver2.herokuapp.com/api/v0.1/books` の返事は５０３状態です．わざわざAPIサーバのプロトタイプがオフになっていますか？

**Comment by ksato9700** [comment]
@AndrewDang-Tran 
I'm sorry, I have to migrate the MongoDB used by the pubserver. I will fix it in the new year holidays.

**Comment by AndrewDang-Tran** [comment]
No worries! I just wanted to make sure it wasn't a permanent thing to see if I had to change sources for japanese texts. Thanks for setting this up in the first place! Happy holidays!

**Comment by ksato9700** [comment]
@AndrewDang-Tran The pubserver2 should be working now. Please try!
